name: Auto Merge on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: self-hosted

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Approve and merge PR
        if: contains(github.head_ref, 'sample_add')
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review "$PR_URL" --approve
          gh pr merge "$PR_URL" --merge
