name: Auto Approve and Merge on PR Creation

on:
  pull_request:
    types: [opened]

jobs:
  auto-approve:
    runs-on: self-hosted
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Approve PR
        if: contains(github.head_ref, 'sample_add')
        run: gh pr review "$PR_URL" --approve

  auto-merge:
    runs-on: self-hosted
    needs: auto-approve
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Merge PR
        run: gh pr merge "$PR_URL" --auto --merge
